name: CI

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master", "develop" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      #테스트 단계 제거하고, 빌드할 때 테스트만 제외
      - name: Build (skip tests)
        run: ./gradlew build -x test --no-daemon