INSERT INTO interest (name) VALUES ('음악');
INSERT INTO interest (name) VALUES ('영화');
INSERT INTO interest (name) VALUES ('운동');
INSERT INTO interest (name) VALUES ('독서');
INSERT INTO interest (name) VALUES ('게임');
INSERT INTO interest (name) VALUES ('요리');
INSERT INTO interest (name) VALUES ('여행');
INSERT INTO interest (name) VALUES ('등산');
INSERT INTO interest (name) VALUES ('사진');
INSERT INTO interest (name) VALUES ('패션');
INSERT INTO interest (name) VALUES ('그림');
INSERT INTO interest (name) VALUES ('춤');
INSERT INTO interest (name) VALUES ('악기 연주');
INSERT INTO interest (name) VALUES ('드라마 감상');
INSERT INTO interest (name) VALUES ('아이돌');
INSERT INTO interest (name) VALUES ('자전거');
INSERT INTO interest (name) VALUES ('러닝');
INSERT INTO interest (name) VALUES ('캠핑');
INSERT INTO interest (name) VALUES ('보드게임');
INSERT INTO interest (name) VALUES ('전시회 관람');
INSERT INTO interest (name) VALUES ('미술관');
INSERT INTO interest (name) VALUES ('공연 관람');
INSERT INTO interest (name) VALUES ('수공예');
INSERT INTO interest (name) VALUES ('일기쓰기');
INSERT INTO interest (name) VALUES ('블로그');
INSERT INTO interest (name) VALUES ('디자인');
INSERT INTO interest (name) VALUES ('IT 기술');
INSERT INTO interest (name) VALUES ('자기계발');
INSERT INTO interest (name) VALUES ('봉사활동');
INSERT INTO interest (name) VALUES ('명상');
